### ISSUE TITLE
Ask for trained model

### ISSUE THREAD

**Issue by zhyx12** [chaoqichen/HTCN#12]
Thanks for your great work, I want to do some analysis based on the trained model and I would be really appreciated if you can share your trained model(cityscapes->foggy cityscapes) with me.

**Comment by chaoqichen** [comment]
@zhyx12 
Hi! Could I share you a link via Baidu Wangpan? I cannot access Google at this moment.

**Comment by chaoqichen** [comment]
@zhyx12 I am working on a CVPR 2021 submission. So if it is not very urgent for you, could I share it after the CVPR ddl?

**Comment by zhyx12** [comment]
I cannot access Google either...you can share the Badu Wangpan if it's convenient for you. Thank you so much.

**Comment by chaoqichen** [comment]
@zhyx12 
链接：https://pan.baidu.com/s/1Vrki-fKoej6PPrEnxkr7YA 
提取码：ew2k

**Comment by zhyx12** [comment]
Thank you very much! It really helps 👍

**Comment by zhyx12** [comment]
Hi Chaoqi, sorry to bother you again, I have test with the shared model, but the result is around 38.5 in city2foggy, I think there might be some error in my python environment or generated annotations of foggy cityscapes, can you share the xml annotation files of foggy cityscapes? Thank you so much!

**Comment by chaoqichen** [comment]
@zhyx12 
Hi! Our testing result is 40.3 mAP. Since the original resource is saved in another server, I can share the XML annotation files of foggy cityscapes with you in the next week (Nov. 17 or 18 after the cvpr ddl).

**Comment by chaoqichen** [comment]
@zhyx12 
Hi! Our testing result is 39.8 mAP. Since the original resource is saved in another server, I can share the XML annotation files of foggy cityscapes with you in the next week (Nov. 17 or 18 after the cvpr ddl).

**Comment by zhyx12** [comment]
OK，Thanks a lot!

**Comment by chaoqichen** [comment]
@zhyx12 
链接：https://pan.baidu.com/s/1RL1fbuc_UOi5NfRQhE5q2g 
提取码：c8n9

**Comment by TADanton** [comment]
Dear Chaoqi,

since the link seems to already expire, may I ask whether you could share a new link for cityscapes foggy annotations?

Thanks a lot for your help!
