### ISSUE TITLE
Cityscapes foggy annotations in voc form

### ISSUE THREAD

**Issue by TADanton** [chaoqichen/HTCN#15]
Dear Chaoqi,

since the link seems to already expire, may I ask whether you could share a new link for cityscapes foggy annotations?

Thanks a lot for your help!

_Originally posted by @TADanton in https://github.com/chaoqichen/HTCN/issues/12#issuecomment-747370136_

**Comment by TADanton** [comment]
sorry to bother you, it's solved

**Comment by Fly-dream12** [comment]
Can you share the voc format annotations, Thanks. @TADanton
