### ISSUE TITLE
Ask for trained model again.

### ISSUE THREAD

**Issue by KosumosuL** [chaoqichen/HTCN#20]
Can you share your trained model on Cityscapes to Foggy Cityscapes (mAP=39.8%)? since previous link has inspired.

**Comment by chaoqichen** [comment]
@KosumosuL 
Below is a permalink. 
链接：https://pan.baidu.com/s/1m9k9ZiJikZRNyF6QbF2Esg 
提取码：2tk0

**Comment by KosumosuL** [comment]
Surprised by your efficiency, you are a temporary god.
