### ISSUE TITLE
pytorch version and cuda version are in conflict

### ISSUE THREAD

**Issue by LiewFeng** [chaoqichen/HTCN#3]
In the readme:
Please follow faster-rcnn respository to setup the environment. In this project, we use Pytorch 1.0.1 and CUDA version is 10.1.

I ran this code:
conda install pytorch=1.0.1 torchvision cudatoolkit=10.1

Then I got this:
UnsatisfiableError: The following specifications were found to be in conflict:
  - cudatoolkit 10.1*
  - pytorch 1.0.1* -> cudatoolkit >=10.0.130,<10.1.0a0

Are there anything wrong with my settings?

**Comment by chaoqichen** [comment]
@PhoneSix Since it requires cudatoolkit >=10.0.130, you can try cudatoolkit=10.0.130.

**Comment by chaoqichen** [comment]
@PhoneSix I just checked that our Cuda version is 10.0.130.

**Comment by chaoqichen** [comment]
I just checked that our CUDA version is 10.0.130. The readme has been modified accordingly. Thank you for your question.

**Comment by chaoqichen** [comment]
@PhoneSix I just checked that our CUDA version is 10.0.130. The readme has been modified accordingly. Thank you for your question.

**Comment by LiewFeng** [comment]
Okay, it works now. Thank you! @chaoqichen
