### ISSUE TITLE
Import errors

### ISSUE THREAD

**Issue by LiewFeng** [chaoqichen/HTCN#4]
Hi, @chaoqichen  I got  import errors.
I ran this code:
`python setup.py build develop`
and got this result:
`Installed /userhome/HTCN/lib
Processing dependencies for faster-rcnn==0.0.0
Finished processing dependencies for faster-rcnn==0.0.0`

But when I ran the train code of this repo
I got an import error
`  File "/userhome/evns/HTCN/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.`

Then I tried to run this code:
`sh make.sh`
I  got the same import error:
`File "/userhome/evns/HTCN/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead`

I've seen many related issues in the [faster r-cnn](https://github.com/jwyang/faster-rcnn.pytorch) repo, but couldn't find a solution.
I use the same version of pytorch as you.
Do I need to run `sh make.sh` after running `python setup.py build develop` ?
If so, is this because my python version is 3.6 and which version do you use? How do you solve it?
I saw this in the readme of [faster r-cnn](https://github.com/jwyang/faster-rcnn.pytorch) :
For code:
`cd lib
python setup.py build develop`
It will compile all the modules you need, including NMS, ROI_Pooing, ROI_Align and ROI_Crop. The default version is compiled with Python 2.7, please compile by yourself if you are using a different python version.
Do you use python 2.7 or you compile by yourself?

When I ran test code of this repo, I got another import error:
`  File "test_net_HTCN.py", line 22, in <module>
    from model.roi_layers import nms
ModuleNotFoundError: No module named 'model.roi_layers'`

I checked the code, there is no directory as lib/model/roi_layers
but I found that you comment a line of code in test_net_HTCN.py
# from model.nms.nms_wrapper import nms
from model.roi_layers import nms

should I use the commented line?

**Comment by chaoqichen** [comment]
@PhoneSix The default pytorch version of the faster-rcnn is 0.4, while you need the 1.0 version. I have updated the related source codes. Please download the full project. Thank you.

**Comment by chaoqichen** [comment]
@PhoneSix If there exist any other problems, please feel free to contact me.

**Comment by LiewFeng** [comment]
@chaoqichen  Still get the same import error for the new code.

But when I ran the code with pytorch 0.4.0, the aforementioned error didn't appear any more, for both the old code and the new code

Maybe it should be pytorch 0.4.0 in the readme?

**Comment by LiewFeng** [comment]
@chaoqichen The setup.py and make.sh in this repo is the same as [faster r-cnn pytorch 0.4.0 version](https://github.com/jwyang/faster-rcnn.pytorch/tree/master/lib), different from [faster r-cnn pytorch 1.0 version](https://github.com/jwyang/faster-rcnn.pytorch/blob/pytorch-1.0/lib)
But in the readme of this repo, the pytorch version is 1.0.1.
It really gets me confused.

**Comment by chaoqichen** [comment]
@PhoneSix I am now working at home and the access to our server is very unstable, I will handle all your mentioned problems today or tomorrow. Thank you for your interest.

**Comment by chaoqichen** [comment]
@PhoneSix Hi! I have fixed the problem, please download the latest version.

**Comment by LiewFeng** [comment]
@chaoqichen I used the latest code but got another error
I ran `python setup.py build develop` then got this:
`Creating /userhome/evns/HTCN2/lib/python3.6/site-packages/faster-rcnn.egg-link (link to .)
Adding faster-rcnn 0.1 to easy-install.pth file

Installed /userhome/HTCN/lib
Processing dependencies for faster-rcnn==0.1
Finished processing dependencies for faster-rcnn==0.1`

but when ran the train code, I got a ModuleNotFoundError
`Traceback (most recent call last):
  File "trainval_net_HTCN.py", line 19, in <module>
    from roi_data_layer.roidb import combined_roidb
  File "/userhome/HTCN/lib/roi_data_layer/roidb.py", line 9, in <module>
    from datasets.factory import get_imdb
  File "/userhome/HTCN/lib/datasets/factory.py", line 14, in <module>
    from datasets.pascal_voc import pascal_voc
  File "/userhome/HTCN/lib/datasets/pascal_voc.py", line 23, in <module>
    from .imdb import imdb
  File "/userhome/HTCN/lib/datasets/imdb.py", line 14, in <module>
    from model.utils.cython_bbox import bbox_overlaps
ModuleNotFoundError: No module named 'model.utils.cython_bbox'`

with newly_established environment of pytorch 1.0.1 and cuda 10.0.130 and python 3.6

**Comment by LiewFeng** [comment]
@chaoqichen  I also got this when I ran `python setup.py build develop`:
`cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++`

**Comment by LiewFeng** [comment]
@chaoqichen a more complete description :
`gcc -pthread -B /userhome/evns/HTCN2/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/userhome/HTCN/lib/model/csrc -I/userhome/evns/HTCN2/lib/python3.6/site-packages/torch/lib/include -I/userhome/evns/HTCN2/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/userhome/evns/HTCN2/lib/python3.6/site-packages/torch/lib/include/TH -I/userhome/evns/HTCN2/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/userhome/evns/HTCN2/include/python3.6m -c /userhome/HTCN/lib/model/csrc/vision.cpp -o build/temp.linux-x86_64-3.6/userhome/HTCN/lib/model/csrc/vision.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++`

**Comment by LiewFeng** [comment]
@chaoqichen Maybe [this](https://github.com/jwyang/faster-rcnn.pytorch/issues/396#issuecomment-447473338) can be a reference ?

**Comment by chaoqichen** [comment]
@PhoneSix Yes. I think you can refer to the issue of faster rcnn (pytorch). The reported problems are associated with your environment. BTW, I use python 3.7.1.

**Comment by LiewFeng** [comment]
@chaoqichen Python 3.7.1 did work for me. Error `ModuleNotFoundError: No module named 'model.utils.cython_bbox'` didn't appear. Maybe you can add it to the readme.

But I still got an import error with the latest code. 
`File "/userhome/evns/HTCN/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 1, in <module> raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.") ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.`

And got some other errors after I fixed this error.

I searched for some time and found that some parts of code are still using the code of pytorch 0.4.0 version faster r-cnn. I solve it by the following modifications:

In lib/model/rpn/proposal_layer.py lin20,  
`from model.nms.nms_wrapper import nms`  → `from model.roi_layers import nms`

In lib/model/rpn/proposal_layer.py lin150,  
`keep_idx_i = nms(torch.cat((proposals_single, scores_single), 1), nms_thresh, force_cpu=not cfg.USE_GPU_NMS)` →
`keep_idx_i = nms(proposals_single, scores_single.squeeze(1), nms_thresh)`

In lib/model/rpn/rpn.py lin77, 
`rois = self.RPN_proposal((rpn_cls_prob.data, rpn_bbox_pred.data,im_info, cfg_key),target=target)` →
`rois = self.RPN_proposal((rpn_cls_prob.data, rpn_bbox_pred.data, im_info, cfg_key))`

After these modifications, it worked.

Simply replacing lib/model/rpn with [this](https://github.com/jwyang/faster-rcnn.pytorch/tree/pytorch-1.0/lib/model/rpn) also works.
